// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOMfMMDN_D4NTk-Us5OTqlIDKsp_F07Wo',
    appId: '1:110263245644:web:fe247edca609ecd6b34de9',
    messagingSenderId: '110263245644',
    projectId: 'praktikum-mobile-f081a',
    authDomain: 'praktikum-mobile-f081a.firebaseapp.com',
    storageBucket: 'praktikum-mobile-f081a.firebasestorage.app',
    measurementId: 'G-B8TYD0NWYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc46L20Li5Z0ffZ_dDdCn4druSDFB5kcM',
    appId: '1:110263245644:android:3c3f81468f149dcab34de9',
    messagingSenderId: '110263245644',
    projectId: 'praktikum-mobile-f081a',
    storageBucket: 'praktikum-mobile-f081a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAyuR2WshukR757l6KdMiug4LznsW1JIk',
    appId: '1:110263245644:ios:b8a5174d8a62dafeb34de9',
    messagingSenderId: '110263245644',
    projectId: 'praktikum-mobile-f081a',
    storageBucket: 'praktikum-mobile-f081a.firebasestorage.app',
    iosBundleId: 'com.example.p9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAyuR2WshukR757l6KdMiug4LznsW1JIk',
    appId: '1:110263245644:ios:b8a5174d8a62dafeb34de9',
    messagingSenderId: '110263245644',
    projectId: 'praktikum-mobile-f081a',
    storageBucket: 'praktikum-mobile-f081a.firebasestorage.app',
    iosBundleId: 'com.example.p9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOMfMMDN_D4NTk-Us5OTqlIDKsp_F07Wo',
    appId: '1:110263245644:web:e22a17f6ff2cc577b34de9',
    messagingSenderId: '110263245644',
    projectId: 'praktikum-mobile-f081a',
    authDomain: 'praktikum-mobile-f081a.firebaseapp.com',
    storageBucket: 'praktikum-mobile-f081a.firebasestorage.app',
    measurementId: 'G-1RG77NKGWE',
  );
}
